
using Asp.Versioning;
using FluentValidation;
using FluentValidation.AspNetCore;
using GlobalECommerce.Api.Configuration;
using GlobalECommerce.Api.Middleware;
using GlobalECommerce.Application.Catalog.Interfaces;
using GlobalECommerce.Application.Catalog.Services;
using GlobalECommerce.Application.Orders.Commands.CreateOrder;
using GlobalECommerce.Application.Orders.Interfaces;
using GlobalECommerce.Application.Orders.Services;
using GlobalECommerce.Application.Payments.Interfaces;
using GlobalECommerce.Application.Payments.Services;
using GlobalECommerce.Infrastructure.Database;
using GlobalECommerce.Infrastructure.Repositories;
using Microsoft.AspNetCore.Mvc;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen();

builder.Services.AddApiVersioning(options =>
{
    options.DefaultApiVersion = new ApiVersion(1, 0);

    options.AssumeDefaultVersionWhenUnspecified = true;

    options.ReportApiVersions = true;
});

builder.Services.AddCors(options =>
{
    options.AddPolicy("Angular",
        builder =>
        {
            builder

                .AllowAnyHeader()

                .AllowAnyMethod()

                .AllowCredentials()

                .WithOrigins("http://localhost:4200");
        });
});
builder.Services.AddFluentValidationAutoValidation();

builder.Services.AddValidatorsFromAssemblyContaining<Program>();
builder.Services.Configure<DatabaseOptions>(
builder.Configuration.GetSection("Database"));

builder.Services.Configure<ApiBehaviorOptions>(options =>
{
    options.InvalidModelStateResponseFactory = context =>
    {
        var errors = context.ModelState
            .Where(x => x.Value?.Errors.Count > 0)
            .Select(x => new
            {
                Field = x.Key,
                Errors = x.Value!.Errors.Select(e => e.ErrorMessage)
            });

        return new BadRequestObjectResult(new
        {
            Message = "Validation Failed",
            Errors = errors
        });
    };
});
// Services
builder.Services.AddSingleton(
new DbConnectionFactory(
builder.Configuration.GetConnectionString("DefaultConnection")!));

builder.Services.AddSingleton<DbInitializer>();

builder.Services.AddSingleton<SeedData>();

builder.Services.AddScoped<IProductRepository, ProductRepository>();
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<IOrderRepository, OrderRepository>();
builder.Services.AddScoped<IOrderService, OrderService>();
builder.Services.AddScoped<IPaymentService, PaymentService>();
builder.Services.AddScoped<IOrderRepository, OrderRepository>();
builder.Services.AddScoped<CreateOrderHandler>();



builder.Host.UseSerilog((ctx, lc) =>
{
    lc.WriteTo.Console();
});

var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI();
app.UseMiddleware<ExceptionMiddleware>();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.UseCors("Angular");
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<DbInitializer>();

    await db.InitializeAsync();

    var seed = scope.ServiceProvider.GetRequiredService<SeedData>();

    await seed.SeedAsync();
}
app.Run();


#region Autogenerated code
//var builder = WebApplication.CreateBuilder(args);

//// Add services to the container.
//// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
//builder.Services.AddOpenApi();

//var app = builder.Build();

//// Configure the HTTP request pipeline.
//if (app.Environment.IsDevelopment())
//{
//    app.MapOpenApi();
//}

//app.UseHttpsRedirection();

//var summaries = new[]
//{
//    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
//};

//app.MapGet("/weatherforecast", () =>
//{
//    var forecast =  Enumerable.Range(1, 5).Select(index =>
//        new WeatherForecast
//        (
//            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
//            Random.Shared.Next(-20, 55),
//            summaries[Random.Shared.Next(summaries.Length)]
//        ))
//        .ToArray();
//    return forecast;
//})
//.WithName("GetWeatherForecast");

//app.Run();

//record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
//{
//    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
//}

#endregion